#!/usr/bin/python

import os

PROJECT = 'conifer-syrup'
LOCALES = ['en_US', 'fr_CA']

# extraction

os.system('pybabel extract -F babel.cfg -o locale/%(PROJECT)s.pot .' % vars())

for locale in LOCALES:
    fn = 'locale/%(locale)s/LC_MESSAGES/%(PROJECT)s.po' % vars()
    if not os.path.isfile(fn):
        os.system('pybabel init -D %(PROJECT)s -i locale/%(PROJECT)s.pot -d locale -l %(locale)s' % vars())

# do the update

os.system('pybabel update -D %(PROJECT)s -i locale/%(PROJECT)s.pot -d locale' % vars())

# compile to .mo

os.system('pybabel compile -D %(PROJECT)s -d locale' % vars())
