* Tasks for the =2010-02-campus-integration-reorg= branch

  The goal of this branch is to reorganize and document the two major
  integration points in Syrup: the library systems and the campus
  information systems. Both of these integrations existed prior to the
  branch, but were undocumented and messy.

** The Evergreen-or-not question. 
   - Prepare to sync with the =eg-schema-experiment= branch
   - "in evergreen database" vs. "other database with OpenSRF calls"

** Enumerate the ways that campus integration is currently used.
   Put this in the campus-integration documentation.

** A Library Integration module which is readable and documented
   - integrate via local_settings.py
   - Prepare to sync with the =eg-schema-experiment= branch

** How much of the integration data belongs in the database?
   Should the Django ADMINS list be pulled from the db? What about
   Z39.50 targets? What are the deciding principles when figuring out
   where to store config data?

** Campus integration for departments.
   - how to address the faculty/campus/dept/etc. hierarchy?
   - list of departments
   - look up department based on course-code
   - instructors in a given department

** question: Campus integration for terms?
   Even just a "feed of terms you might not yet know about?"

** question: when looking up membership info, always update membership table?
   Should just asking an external campus system, 'What sections is
   John in?' automatically add membership records for John, for
   course-sites related to those sections? Should it also (only during
   the active period of a term) drop John from current sections that
   he's no longer part of?
