#!/usr/local/bin/python-oracle-cgi-wrapper
# -*- mode: python -*-

import os
import cgi
import cx_Oracle
import simplejson
import re

CONN_STRING = '***/***@********'
conn = cx_Oracle.connect(CONN_STRING)
#import cgitb; cgitb.enable(display=True)

def memberships(uid):
    q = ("select realm_id, role_name, S.title, DBMS_LOB.SUBSTR(P.value, 64) "
         "from sakai_realm_rl_gr G "
         "left join sakai_realm R on G.realm_key = R.realm_key "
         "left join sakai_user_id_map M on G.user_id=M.user_id "
	 "left join sakai_site S on S.site_id = substr(R.realm_id, 7) "
         "left join sakai_realm_role RR on G.role_key = RR.role_key "
	 "left join sakai_site_property P on P.site_id = S.site_id and P.name='term_code' "
         "where eid=:1 and active=1 "
         "and regexp_like(realm_id, '^/site/.{36}$') ")
    cursor = conn.cursor()
    cursor.execute(q, (uid,))
    coursepat = re.compile(r'^(\d\d-\d\d-\d\d\d)')
    for realm, role, title, term in cursor.fetchall():
        site = realm[6:]
        tmp = coursepat.match(title)
        course = tmp and tmp.group(1) or None
        # term: convert 'W08+S08' to ['2008W', '2008S']
        try:
            terms = ['20%s%s' % (t[-2:], t[0]) for t in term.split('+')]
        except:
            terms = []
        yield {'site': site, 'role': role, 'title': title, 'terms': terms, 
               'course': course}

form = cgi.FieldStorage()
uid  = form['uid'].value
compress = 'deflate' in os.environ.get('HTTP_ACCEPT_ENCODING', '')
resp = simplejson.dumps(list(memberships(uid)))

print 'Status: 200 OK'
print 'Content-Type: application/json'
if compress:
    import zlib
    print 'Content-Encoding: deflate'
    print
    print zlib.compress(resp)
else:
    print
    print resp
