#!/usr/local/bin/python-oracle-cgi-wrapper
# -*- mode: python -*-

import os
import cx_Oracle
import simplejson as json
import cgitb
#cgitb.enable(display=True)

CONN_STRING = '***/***@********'
conn = cx_Oracle.connect(CONN_STRING)

try:
    siteid = os.environ['PATH_INFO'][1:]
    assert len(siteid) == 36, 'malformed site id'

    cursor = conn.cursor()
    query = """
    select provider_id from sakai_realm
    where realm_id like '/site/' || :1
    """
    cursor.execute(query, (siteid,))
    try:
        provider_id = cursor.fetchone()[0] or ''
    except:
        raise Exception('site ID not found.')

    providers = provider_id.split('+')
    output = json.dumps({'status':'ok', 'siteid': siteid, 'providers': providers})
except Exception, e:
    output = {'status':'error', 'error': str(e)}

print 'Status: 200 OK'
print 'Content-Type: application/json'
print
print output
conn.close()
