# Do not edit this file: make your own, instead.

# See COURSE_CODES.txt for information.

course_code_is_valid       = None
course_code_example        = None
course_code_list           = None
course_code_lookup_title   = None
course_code_cross_listings = None

# See COURSE_SECTIONS.txt for information.

sections_tuple_delimiter   = '|'
sections_taught_by         = lambda u: []
students_in                = lambda *sections: set()
instructors_in             = lambda *sections: set()
sections_for_code_and_term = lambda code, term: []

